services:
  api:
    image: simple2b/project-s-api
    ports:
      - 127.0.0.1:${API_PORT:-7888}:80
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-pass}
      APP_PORT: 80
      OPENAI_API_KEY: ${OPENAI_API_KEY:-''}
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-pass}
    volumes:
      - db_data:/data/db
    ports:
      - 127.0.0.1:${MONGO_LOCAL_PORT:-27017}:27017

volumes:
  db_data:
