services:
  api:
    # image: atlas-api
    #TODO: replace with real image
    ports:
      - 127.0.0.1:${API_PORT:-7888}:80
    environment:
      - TESTING=1
      - TZ=Europe/Kyiv
      - APP_PORT=80
