#!/bin/bash

# get major, minor or patcgh version from script arugment

# Ensure that the user has provided a valid argument
case $1 in
    patch)
        ;;
    minor)
        ;;
    major)
        ;;
    *)
        echo "Usage: $0 [patch|minor|major]"
        VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $VERSION"
        exit 1
        ;;
esac

# Ensure that the working directory is clean
if [[ $(git status -s) ]]
then
    echo "Working directory is not clean! Please commit all changes before running this script."
    exit 1
fi

# Ensure that the local branch is up to date with the remote branch
git pull

# goto script directory
cd "$(dirname "$0")"

npm version $1

if [ $? -ne 0 ]; then
  exit 1
fi

git push --follow-tags
