/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.6
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateUser,
  HTTPValidationError,
  Token,
  User,
  UserLogin
} from '.././model'



/**
 * @summary Token
 */
export const aPIToken = (
    userLogin: UserLogin, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Token>> => {
    
    return axios.default.post(
      `/api/auth/token`,
      userLogin,options
    );
  }



export const getAPITokenMutationOptions = <TError = AxiosError<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aPIToken>>, TError,{data: UserLogin}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof aPIToken>>, TError,{data: UserLogin}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof aPIToken>>, {data: UserLogin}> = (props) => {
          const {data} = props ?? {};

          return  aPIToken(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type APITokenMutationResult = NonNullable<Awaited<ReturnType<typeof aPIToken>>>
    export type APITokenMutationBody = UserLogin
    export type APITokenMutationError = AxiosError<void | HTTPValidationError>

    /**
 * @summary Token
 */
export const useAPIToken = <TError = AxiosError<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aPIToken>>, TError,{data: UserLogin}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof aPIToken>>,
        TError,
        {data: UserLogin},
        TContext
      > => {

      const mutationOptions = getAPITokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Register
 */
export const aPIRegister = (
    createUser: CreateUser, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    
    return axios.default.post(
      `/api/auth/register`,
      createUser,options
    );
  }



export const getAPIRegisterMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aPIRegister>>, TError,{data: CreateUser}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof aPIRegister>>, TError,{data: CreateUser}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof aPIRegister>>, {data: CreateUser}> = (props) => {
          const {data} = props ?? {};

          return  aPIRegister(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type APIRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof aPIRegister>>>
    export type APIRegisterMutationBody = CreateUser
    export type APIRegisterMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Register
 */
export const useAPIRegister = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aPIRegister>>, TError,{data: CreateUser}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof aPIRegister>>,
        TError,
        {data: CreateUser},
        TContext
      > => {

      const mutationOptions = getAPIRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    