/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.4
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw'


export const getRootRootMockHandler = () => {
  return http.get('*/', async () => {await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getRootWildcardPathMockHandler = () => {
  return http.get('*/:wildcardPath', async () => {await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getRootMock = () => [
  getRootRootMockHandler(),
  getRootWildcardPathMockHandler()
]
